# Hands on Linear Algebra with Python
## Foreword

Based on <i>Einführung in Data Science</i> by Joel Grus, this notebook attempts to tackle the fundamentals of linear algebra with python. For me, it's important to go into more detail for, yet, I don't feel confident enough to deal data science without knowing about the mathematical fundamentals. So, this notebook is an attempt to fill that gap.


But before I start, I need to do some mandatory stuff like importing libraries and initialising a logger.

In [1]:
# Import libraries
import logging
import numpy as np

In [2]:
# Initialise Logger
log = logging.getLogger('linear_algebra_notebook')
log.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

fh = logging.FileHandler('log/linear_algebra.log')
fh.setLevel(logging.INFO)
fh.setFormatter(formatter)

log.addHandler(fh)

## Matrices 
In general, matrices can be thought of like n-dimensional arrays. That means a matrix can have <i>n</i> rows and <i>m</i> columns.
### Formula
<center>
$$
A_{m,n} = 
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
 \end{pmatrix}
 $$
</center>

To specifiy the position of an element within a matrix something like $a_{n,m}$ is used. In this very notation, $n$ determines the row whereas $m$ determines the column in which the element can be found.
### Example
<center>
$$
A = \begin{pmatrix}
    1 & 4 \\
    9 & 5 \\
    8 & 0
    \end{pmatrix}
$$
</center>

Following what is said above, the element at position $A_{3,1}$ is $8$.

### Addition of two matrices
If you want to add up two matrices, make sure both matrices do have the same dimension. Meaning both must have the same number of rows and the same number of columns.
<center>
$$
A = \begin{pmatrix}
    a_{1,1} & a_{1,2} \\
    a_{2,1} & a_{2,2} \\
    a_{3,1} & a_{3,2}
    \end{pmatrix}
    ;
B = \begin{pmatrix}
    b_{1,1} & b_{1,2} \\
    b_{2,1} & b_{2,2} \\
    b_{3,1} & b_{3,2}
    \end{pmatrix}
$$
</center>

In this case, adding up $A$ and $B$ is possible because both have the same dimension. So, we can do the following:


<center>
$$
\begin{pmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2} \\
a_{3,1} & a_{3,2}
\end{pmatrix}
+
\begin{pmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \\
b_{3,1} & b_{3,2}
\end{pmatrix}
=
\begin{pmatrix}
a_{1,1} + b_{1,1} & a_{1,2} + b_{1,2}\\
a_{2,1} + b_{2,1} & a_{2,2} + b_{2,2}\\
a_{3,1} + b_{3,1} & a_{3,2} + b_{3,2}
\end{pmatrix}
$$
</center>

But adding up two matrices that do not share the same dimensions is not possible:

<center>
$$
A = \begin{pmatrix}
    a_{1,1} & a_{1,2} \\
    a_{2,1} & a_{2,2} \\
    a_{3,1} & a_{3,2}
    \end{pmatrix}
    ;
B = \begin{pmatrix}
    b_{1,1} & b_{1,2} \\
    b_{2,1} & b_{2,2} \\
    \end{pmatrix}
$$
</center>

In the latter case, adding up $A$ and $B$ is not possible they do not share the same dimension.

Now let's check out how this would be done in python.

In [3]:
# Function to sum up two matrices a and b with only one dimension without using a specialised package
def sum_two_one_dimensional_matrices(v_a, v_b):
    log.info('checking length of matrices a ' + str(v_a) +  ' and matrices b ' + str(v_b))
    if len(v_a) is len(v_b):
        log.info('sum up matrices a and vector b.')
        result = []
        for i in range(0, len(v_a)):
            tmp = v_a[i] + v_b[i]
            result.append(tmp)
        log.info('result: ' + str(result))
        return result
    else:
        log.error('matrices must have the same length.')
        return None

    
# Function to sum up matrices n dimensions without using a specialised package
def sum_two_n_dimensional_matrices_difficultly(nd_v_a, nd_v_b):
    log.info('checking length of matrices a ' + str(v_a) +  ' and matrices b ' + str(v_b))
    final = []
    if len(nd_v_a) is len(nd_v_b):
        for i in range(0, len(nd_v_a)):
            tmp_a = nd_v_a[i]
            tmp_b = nd_v_b[i]
            result = []
            if len(tmp_a) is len(tmp_b):
                for j in range(0, len(tmp_a)):
                    tmp = tmp_a[j] + tmp_b[j]
                    result.append(tmp)
            else:
                log.error('columns must have the same length.')
                return None
            final.append(result)
        log.info('result: ' + str(result))
        return final
    else:
        log.error('matrices must have the same length.')
        return None
    
    
# Function to sum up to n-dimension matrices using numpy
def sum_up_two_n_dimensional_matrices(nd_v_a, nd_v_b):
    log.info('checking length of matrices a ' + str(v_a) +  ' and matrices b ' + str(v_b))
    return nd_v_a + nd_v_b

In [4]:
# first function - positive case
v_a = [1,5,0]
v_b = [2,6,4]
result = sum_two_one_dimensional_matrices(v_a, v_b)
print(result)

[3, 11, 4]


In [5]:
# negative function - positive case
v_a = [1,5]
v_b = [2,6,4]
result = sum_two_one_dimensional_matrices(v_a, v_b)
print(result)

None


In [6]:
# second function - positive case
nd_v_a = [[1,5,9], [6,2,1]]
nd_v_b = [[7,8,3], [1,1,1]]
result = sum_two_n_dimensional_matrices_difficultly(nd_v_a, nd_v_b)
print(result)

[[8, 13, 12], [7, 3, 2]]


In [7]:
# second function - negative case
nd_v_a = [[1,5,9], [6,2]]
nd_v_b = [[7,8,3], [1,1,1]]
result = sum_two_n_dimensional_matrices_difficultly(nd_v_a, nd_v_b)
print(result)

None


In [8]:
# thrid function - positive case
nd_v_a = np.array([[1,8,6], [9,7,1]])
nd_v_b = np.array([[3,8,8], [9,0,6]])
result = sum_up_two_n_dimensional_matrices(nd_v_a, nd_v_b)
print(result)

[[ 4 16 14]
 [18  7  7]]


In [9]:
# thrid function - negative case
nd_v_a = np.array([[1,8,6], [7,1]])
nd_v_b = np.array([[3,8,8], [9,0,6]])
result = sum_up_two_n_dimensional_matrices(nd_v_a, nd_v_b)
print(result)

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

Above, I implemented three different functions. The first two functions are implemented from scratch. Meaning I had to think about how to sum up matrices of $n$ dimensions. As you can see, the code became quite large, hard to understand and dissatisfying. Therefore, I implemented a third option using a specialised package. <i>Numpy</i> is a simple yet powerful package for scientific coding that makes life much easier.

The following code blocks just utilise these previously defined functions. These perfectly illustrate what is said before - you cannot sum up vectors that do not have the same dimension.

### Subtraction of two matrices
Like additon, subtraction of two matrices is the same. Here, you need two n-dimensional matrices that share the same dimension. If that is not given, subtraction does not work at all.


<center>
$$
A = \begin{pmatrix}
    a_{1,1} & a_{1,2} \\
    a_{2,1} & a_{2,2} \\
    a_{3,1} & a_{3,2}
    \end{pmatrix}
    ;
B = \begin{pmatrix}
    b_{1,1} & b_{1,2} \\
    b_{2,1} & b_{2,2} \\
    b_{3,1} & b_{3,2}
    \end{pmatrix}
$$
</center>


Here, a subtraction would be possible for the matrices share the same dimensions. So, we can do this:

<center>
$$
\begin{pmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2} \\
a_{3,1} & a_{3,2}
\end{pmatrix}
-
\begin{pmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \\
b_{3,1} & b_{3,2}
\end{pmatrix}
= \begin{pmatrix}
a_{1,1} - b_{1,1} & a_{1,1} - b_{1,2} \\
a_{2,1} - b_{2,1} & a_{2,1} - b_{2,2} \\
a_{3,1} - b_{3,1} & a_{3,1} - b_{3,2}
\end{pmatrix}
$$
</center>

In [10]:
# Function to sum up two vectors a and b with only one dimension without using a specialised package
def subtract_two_one_dimensional_matrices(v_a, v_b):
    log.info('checking length of vector a ' + str(v_a) +  ' and vector b ' + str(v_b))
    if len(v_a) is len(v_b):
        log.info('sum up vector a and vector b.')
        result = []
        for i in range(0, len(v_a)):
            tmp = v_a[i] - v_b[i]
            result.append(tmp)
        log.info('result: ' + str(result))
        return result
    else:
        log.error('vectors must have the same length.')
        return None

    
# Function to sum up vectors n dimensions without using a specialised package
def subtract_two_n_dimensional_matrices_difficultly(nd_v_a, nd_v_b):
    log.info('checking length of vector a ' + str(v_a) +  ' and vector b ' + str(v_b))
    final = []
    if len(nd_v_a) is len(nd_v_b):
        for i in range(0, len(nd_v_a)):
            tmp_a = nd_v_a[i]
            tmp_b = nd_v_b[i]
            result = []
            if len(tmp_a) is len(tmp_b):
                for j in range(0, len(tmp_a)):
                    tmp = tmp_a[j] - tmp_b[j]
                    result.append(tmp)
            else:
                log.error('columns must have the same length.')
                return None
            final.append(result)
        log.info('result: ' + str(result))
        return final
    else:
        log.error('vectors must have the same length.')
        return None
    
    
# Function to sum up to n-dimension vectors using numpy
def subtract_up_two_n_dimensional_matrices(nd_v_a, nd_v_b):
    log.info('checking length of vector a ' + str(v_a) +  ' and vector b ' + str(v_b))
    return nd_v_a - nd_v_b

In [11]:
# first function - positive case
v_a = [1,5,0]
v_b = [2,6,4]
result = subtract_two_one_dimensional_matrices(v_a, v_b)
print(result)

[-1, -1, -4]


In [12]:
# negative function - positive case
v_a = [1,5]
v_b = [2,6,4]
result = subtract_two_one_dimensional_matrices(v_a, v_b)
print(result)

None


In [13]:
# second function - positive case
nd_v_a = [[1,5,9], [6,2,1]]
nd_v_b = [[7,8,3], [1,1,1]]
result = subtract_two_n_dimensional_matrices_difficultly(nd_v_a, nd_v_b)
print(result)

[[-6, -3, 6], [5, 1, 0]]


In [14]:
# second function - negative case
nd_v_a = [[1,5,9], [6,2]]
nd_v_b = [[7,8,3], [1,1,1]]
result = subtract_two_n_dimensional_matrices_difficultly(nd_v_a, nd_v_b)
print(result)

None


In [15]:
# thrid function - positive case
nd_v_a = np.array([[1,8,6], [9,7,1]])
nd_v_b = np.array([[3,8,8], [9,0,6]])
result = subtract_up_two_n_dimensional_matrices(nd_v_a, nd_v_b)
print(result)

[[-2  0 -2]
 [ 0  7 -5]]


In [16]:
# thrid function - negative case
nd_v_a = np.array([[1,8,6], [7,1]])
nd_v_b = np.array([[3,8,8], [9,0,6]])
result = subtract_up_two_n_dimensional_matrices(nd_v_a, nd_v_b)
print(result)

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 